### PR TITLE
rectified nesterov adam

### PR DESCRIPTION
**Pull request by niley1nov**
added class RNAdam which uses nesterov accelerated gradient instead of momentum.

### CODE REVIEW

**Comment by OverLordGoldDragon** [comment]
Is this a valid implementation? Unsure what the "failed check" implies -- thanks

**Comment by CyberZHG** [comment]
@OverLordGoldDragon 

It means there's no unit test for these updates and the coverage decreased. However, @niley1nov had published these changes, you can try it if you're interested.

**Comment by OverLordGoldDragon** [comment]
Tested both RAdam and RNadam; both work, both are stable. Compared with Nadam, RNAdam validation loss was more stable, but didn't observe ultimate F1-score improvement; in fact, optimizer scored .856 vs .882 - perhaps a different warmup schedule would yield improvements.

Thank you both for your implementations.

**Comment by OverLordGoldDragon** [comment]
@niley1nov  Discovered a mistake in decay implementation logic:

```
if self.initial_total_steps > 0:
    warmup_steps = self.total_steps * self.warmup_proportion
    decay_steps = self.total_steps - warmup_steps
    lr = K.switch(
        t <= warmup_steps,
        lr * (t / warmup_steps),
        lr * (1.0 - K.minimum(t, decay_steps) / decay_steps),
    )
```

- `w_p = 1` --> `decay_steps = 0` --> `lr = NaN`
- Even if `w_p < 1`, we must have `decay_steps > warmup_steps` in `K.min`, which _cannot happen_ for `w_p > .5` - else `K.min = 1` and `lr = 0` instantly post-warmup
- Regardless of `decay_steps`, `K.min` ultimately evaluates to `1`, yielding `lr = 0`

(`w_p == warmup_proportion`, `K.min == K.minimum(...)`)

@CyberZHG 's implementation logic is correct, via `min_lr`, bounding the post-decay value.

**Pull request closed without merging**
